Description of get_params
Home > . > get_params.m
get_params
PURPOSE
GET_PARAMS retrieve params saved in a .mat file
SYNOPSIS
function params = get_params(file_name)
DESCRIPTION
 GET_PARAMS retrieve params saved in a .mat file
 INPUT:
       file_name: path of the file to load
$ Author: Jose Marcos Rodriguez $
$ Date: 16-Dec-2013 17:16:31 $
$ Revision : 1.00 $
% FILENAME  : get_params.m
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
convert2gray CONVERT2GRAY converts to gray all JPG, PNG or PPM images found in
get_feature_matrix GET_FEATURE_MATRIX computes the descriptor matrix for all input images
get_pyramid_dimensions GET_PYRAMID_DIMENSIONS function to compute the pyramid dimensions
get_pyramid_hogs GET_PYRAMID_HOGS function computes de HOG descriptor for all the
get_scale_space_pyramid_images GET_SCALE_SPACE_PYRAMID_IMAGES retrieves every window image in a
plot_DETcurve PLOT_DETCURVE function to compute de DET plot given a set of models
plot_reject_curves PLOT_REJECT_CURVES Tests a (lib)SVM classifier from the specified images
test_svm TEST_SVM Tests a (lib)SVM classifier from the specified images paths
test_svm_PCA TEST_SVM_PCA Tests a (lib)SVM classifier from the specified images paths
train_svm TRAIN_SVM Train an SVM classifier with the specified images.
train_svm_PCA TRAIN_SVM_PCA Train an SVM classifier with the specified images.
SOURCE CODE
function params = get_params(file_name)
% GET_PARAMS retrieve params saved in a .mat file
%
% INPUT:
%       file_name: path of the file to load
%
%$ Author: Jose Marcos Rodriguez $
%$ Date: 16-Dec-2013 17:16:31 $
%$ Revision : 1.00 $
%% FILENAME  : get_params.m
   % Testing if param file exists in the params directory
    if exist(['params',filesep,strcat(file_name,'.mat')],'file')
        params = load(['params',filesep,strcat(file_name,'.mat')]);
    % Testing if param file exists in the current directory
    elseif exist(strcat(file_name,'.mat'),'file')
        params = load(strcat(file_name,'.mat'));
    % Dialog to select param file
    else
        [param_file,PathName,~] = uigetfile('*.mat',strcat('Select parameter file (',file_name,')'));
        if ~isa(param_file,'double')
            params = load([PathName,filesep,param_file]);
        else
            cprintf('Errors','Missing param file...\nexiting...\n\n');
            return
        end
    end
end